name: Build Test

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  Letters:
    runs-on: windows-latest
    steps:
      - name: Install AutoHotkey
        uses: ManInDark/AHK-CharacterHelper/Actions/Install-AutoHotkey@master
        with:
          create-cache: true
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Build Letters
        uses: ManInDark/AHK-CharacterHelper/Actions/Compile-AutoHotkey@master
        with:
          script-path: AutoHotkey Script Letters
  SoundControl:
    runs-on: windows-latest
    steps:
      - name: Install AutoHotkey
        uses: ManInDark/AHK-CharacterHelper/Actions/Install-AutoHotkey@master
        with:
          create-cache: true
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Build SoundControl
        uses: ManInDark/AHK-CharacterHelper/Actions/Compile-AutoHotkey@master
        with:
          script-path: AutoHotkey Script SoundControl
  TabletControl:
    runs-on: windows-latest
    steps:
      - name: Install AutoHotkey
        uses: ManInDark/AHK-CharacterHelper/Actions/Install-AutoHotkey@master
        with:
          create-cache: true
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Build TabletControl
        uses: ManInDark/AHK-CharacterHelper/Actions/Compile-AutoHotkey@master
        with:
          script-path: AutoHotkey Script TabletControl
  BingSearcher:
    runs-on: windows-latest
    steps:
      - name: Install AutoHotkey
        uses: ManInDark/AHK-CharacterHelper/Actions/Install-AutoHotkey@master
        with:
          create-cache: true
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Build BingSearcher
        uses: ManInDark/AHK-CharacterHelper/Actions/Compile-AutoHotkey@master
        with:
          script-path: AutoHotkey Script BingSearcher