name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  Letters:
    runs-on: windows-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Install AutoHotkey
        uses: ManInDark/AHK-CharacterHelper/Actions/Install-AutoHotkey@master
      - name: Build Letters
        uses: ManInDark/AHK-CharacterHelper/Actions/Compile-AutoHotkey@master
        with:
          script-path: AutoHotkey Script Letters
  SoundControl:
    runs-on: windows-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Install AutoHotkey
        uses: ManInDark/AHK-CharacterHelper/Actions/Install-AutoHotkey@master
      - name: Build SoundControl
        uses: ManInDark/AHK-CharacterHelper/Actions/Compile-AutoHotkey@master
        with:
          script-path: AutoHotkey Script SoundControl