name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Install AutoHotkey
        uses: ManInDark/AHK-CharacterHelper@master
      - name: Build Letters
        id: build-letters
        run: cmd /C '".\ahk-extracted\Compiler\Ahk2Exe.exe" /in "AutoHotkey Script Letters.ahk" /out "AutoHotkey Script Letters.exe" /silent /base ".\ahk-extracted\Compiler\Unicode 64-bit.bin"';
      - name: Build SoundControl
        id: build-soundcontrol
        run: cmd /C '".\ahk-extracted\Compiler\Ahk2Exe.exe" /in "AutoHotkey Script SoundControl.ahk" /out "AutoHotkey Script SoundControl.exe" /silent /base ".\ahk-extracted\Compiler\Unicode 64-bit.bin"';