name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Master
        uses: actions/checkout@master

      # Runs a single command using the runners shell
      - name: Build
        run: |
          (New-Object System.Net.WebClient).DownloadFile("https://www.autohotkey.com/download/ahk-install.exe", (Get-Location).Path + "\Installer.exe");
          .\Installer.exe /S
          dir
          dir "C:\Program Files"
          dir "C:\Program Files\AutoHotkey"
          dir "C:\Windows\System32\"
          cmd /C CompileAndCopy.cmd
