name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Install AutoHotkey
        id: install-autohotkey
        run: |
          (New-Object System.Net.WebClient).DownloadFile("https://www.autohotkey.com/download/ahk.zip", (Get-Location).Path + "\ahk.zip");
          Expand-Archive .\ahk.zip -DestinationPath .\ahk-extracted\
      - name: Build Letters
        id: build-letters
        run: cmd /C '".\ahk-extracted\Compiler\Ahk2Exe.exe" /in "AutoHotkey Script Letters.ahk" /out "AutoHotkey Script Letters.exe"';
      - name: Build SoundControl
        id: build-soundcontrol
        run: cmd /C '".\ahk-extracted\Compiler\Ahk2Exe.exe" /in "AutoHotkey Script SoundControl.ahk" /out "AutoHotkey Script SoundControl.exe"';