name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Master
        id: checkout
        uses: actions/checkout@master
      - name: Install AutoHotkey
        uses: ManInDark/AHK-CharacterHelper@master
      - name: Build Letters
        id: build-letters
        run: cmd /C '".\ahk-extracted\Compiler\Ahk2Exe.exe" /in "AutoHotkey Script Letters.ahk" /out "AutoHotkey Script Letters.exe" /silent /base ".\ahk-extracted\Compiler\Unicode 64-bit.bin"';
      - name: Build SoundControl
        id: build-soundcontrol
        run: cmd /C '".\ahk-extracted\Compiler\Ahk2Exe.exe" /in "AutoHotkey Script SoundControl.ahk" /out "AutoHotkey Script SoundControl.exe" /silent /base ".\ahk-extracted\Compiler\Unicode 64-bit.bin"';
      - name: Create Release
        uses: ncipollo/release-action@v1 # https://github.com/ncipollo/release-action
        with:
          artifacts: "*.exe,helpfile.txt"
          token: ${{ secrets.GITHUB_TOKEN }}